build:
  version: "1.0"

cards:
  message: "Welcome to the Cards Microservice (PROD profile) from EazyBank"
  contactDetails:
    name: "PROD manager"
    email: "thegera4@hotmail.com"
  onCallSupport:
    - (777)777-1234
    - (777)777-6678