build:
  version: "3.0"

loans:
  message: "Welcome to the Loans Microservice (DEV profile) from EazyBank"
  contactDetails:
    name: "Gerardo Medellin"
    email: "thegera4@hotmail.com"
  onCallSupport:
    - (555)555-1234
    - (555)555-5678