spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:///C://Users//Gerardo//Documents//Web-Development//Java//config"

server:
  port: 8071